config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_up: 'register', sign_out: 'logout'}
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: "portfolio_show"
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs do 
  	member do 
  		get :toggle_status
  	end
  end

  		

root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	has_many :technologies
	has_one_attached :images
	accepts_nested_attributes_for :technologies, 
								reject_if: 	:all_blank, allow_destroy: true

	

validates_presence_of :title, :subtitle, :body, :images


def self.ruby
	where(subtitle: "Ruby on rails")
end
scope :angular, -> {where(subtitle: "Angular")}

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
layout "portfolio"
access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

	def index
		@portfolio_items = Portfolio.all
	end

	def angular
		@angular_portfolio_items = Portfolio.angular
	end

	def new
		@portfolio_item = Portfolio.new
		# 3.times {@portfolio_item.technologies.build}
	end

	def create
    	@portfolio_item = Portfolio.new(portfolio_params)

	    respond_to do |format|
	      if @portfolio_item.save
	        format.html { redirect_to portfolios_path, notice: "Portfolio item is live now" }
	        
	      else
	        format.html { render :new, status: :unprocessable_entity }
	       
	      end
	    end
    end
    def show 
	@portfolio_item = Portfolio.find(params[:id])
	
	end

	def edit
		@portfolio_item = Portfolio.find(params[:id])
		
	end


	def update
			@portfolio_item = Portfolio.find(params[:id])
	    respond_to do |format|
	      if @portfolio_item.update(portfolio_params)
	        format.html { redirect_to portfolios_path, notice: "The record is successfully updated." }
	   
	      else
	        format.html { render :edit, status: :unprocessable_entity }
	       
	      end
	    end
    end

 	
def destroy
   @portfolio_item = Portfolio.find(params[:id])
   @portfolio_item.destroy
   redirect_to '/portfolios'
end

private

def portfolio_params
	params.require(:portfolio).permit(:title, 
									  :subtitle,
									  :body,
									  :main_image,
									  :thumb_image,
									  :images,
									  technologies_attributes: [:name]
									  )
end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper

	def image_generator(height:, width:)
		"https://via.placeholder.com/#{height}x#{width}"
		
	end
	
end

app/views/portfolios/_form.html.erb
<%= form_for @portfolio_item do |f| %>
<% if portfolio_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio_item.errors.count, "error") %> prohibited this portfolio_item from being saved:</h2>

      <ul>
      <% portfolio_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>

      <label class="btn btn-primary">
        <%= f.label :images %>
        <%= f.file_field :images %>
      </lable>

      <div class="form-group">
        <%#= f.label :images %>
        <%#= f.file_field :thumb_image %>
      </div>

    </div>

    


    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>

  <hr>

  <div class="col-md-12">
    <h2>Technolgies Used:</h2>
    <div>
      <%=f.fields_for :technologies do |technology_form| %>
          <%= render 'technology_fields', f: technology_form%>
      <% end %>
    </div>
    <div>
      <%= link_to_add_association 'add task', f, :technologies %>
    </div>
    <div class="form-group">
      <%= f.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<br>
<div class="col-md-4">

  <div class="card mb-4 box-shadow">
  	<%#= tag portfolio_item.thumb_image  unless portfolio_item.thumb_image.nil? %>
  	<%#= image_tag portfolio_item.main_image unless portfolio_item.main_image.nil? %>
    <!-- <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap"> -->
    <%= image_tag portfolio_item.images if portfolio_item.images.present? %>
    <div class="card">
    	
		    <div class="card-body">
		      <p class="card-text"><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %> </p> <%= portfolio_item.subtitle %>
		      <div class="d-flex justify-content-between align-items-center">
		        <div class="btn-group">
		          <%=link_to 'View', portfolio_show_path(portfolio_item),class: "btn btn-sm btn-outline-secondary"%>
		          
		          	<%=link_to 'Edit', edit_portfolio_path(portfolio_item) ,class: "btn btn-sm btn-outline-secondary"%>

		          	<%= link_to 'Delete', portfolio_path(portfolio_item), method: :delete, data: {confirm: "Are you Sure?"},class: "btn btn-sm btn-outline-secondary" if logged_in?(:site_admin) %>
		        </div>
		        <small class="text-muted">9 mins</small>
		      </div>
		    </div>
    </div>
  </div>
</div>





            

app/views/portfolios/_technology_fields.html.erb
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
   <%= link_to_remove_association "remove task", f %>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>
<h2><%= link_to 'New Portfolio',new_portfolio_path if logged_in?(:site_admin) %></h2>

<% @angular_portfolio_items.each do |portfolio_item|%>


	<p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %> </p> 	
	<p><%= portfolio_item.subtitle %> </p> 
	<p><%= portfolio_item.body %> </p> 
	<p><%= image_tag portfolio_item.thumb_image  unless portfolio_item.thumb_image.nil? %></p>
	<%= link_to 'Edit', edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %> |
	<%= link_to 'Delete', portfolio_path(portfolio_item), method: :delete, data: {confirm: "Are you Sure?"} if logged_in?(:site_admin) %>
	<hr>


<%end%>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
  <h1>Edit this Portfolio Item</h1>

  <%= render 'portfolios/form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<%= render partial: 'portfolio_item', collection: @portfolio_items%>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
  <h1>Create a new Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>  
</div>

app/views/portfolios/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <%# = image_tag @portfolio_item.main_image %>
       <%= image_tag @portfolio_item.images, width: '100%' %>
    </div>

    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>

      <hr>

      <em><%= @portfolio_item.subtitle %></em>

      <p><%= @portfolio_item.body %></p>

      <hr>

      <h3>Technologies Used:</h3>

      <% @portfolio_item.technologies.each do |t| %>
      <p><%= t.name %></p>
      <% end %>

      <%= link_to "View All Portfolios", portfolios_path %>
    </div>
  </div>
</div> 